#!/usr/bin/python -tt
import sys
import time
start_time = time.clock()

fiblist = [1,2]
maxfib = 4*10**6
while fiblist[-1]<=maxfib:
	fiblist.append(fiblist[-1]+fiblist[-2])
del fiblist[-1]

fibeven = []
for n in range(len(fiblist)):
	if fiblist[n] % 2 == 0:
		fibeven.append(fiblist[n])

print 'answer = ', sum(fibeven)
print 'clock time = ', time.clock() - start_time, "seconds"

#Q: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
